### ISSUE TITLE
terminate called after throwing an instance of 'std::out_of_range'

### ISSUE THREAD

**Issue by sashulkaSh** [mzytnicki/tedna#3]
Hello ! 
My ran on server with 64gb RAM and 12 cores :
`tedna --max-reads 10000000 --processors 11 -1 R1.fastq -2 R2.fastq -k 61 -i 250 -t 50 -o file `
with reads ~20 000 000 nt

I had the following problem :
	
	
```......
	2560000/2610612 comparisons.
	2570000/2610612 comparisons.
	2580000/2610612 comparisons.
	2590000/2610612 comparisons.
	2600000/2610612 comparisons.
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr: __pos (which is 18446744073709551482) > this->size() (which is 328)

```
and then  
`Aborted (core dumped)`

the situation is repeated with restart (only the numbers following the words "which is" are changing)

**Comment by mzytnicki** [comment]
Hello,
I thank you very much for your feedback.  Unfortunately, it is difficult (impossible?) for me to debug with this log.
Would it possible for you to share your data?
I promise I will remove them from my PC (and not use them for anything but debugging) as soon as the bug is found.
You can share the link using my personal email (at the end of the README).
Does that seem doable for you?

**Comment by sashulkaSh** [comment]
Yes, I will send files as soon as I download them on a PC! Thank you

**Comment by sashulkaSh** [comment]
Hmmmm, I found that when I reduced the number of processors to 10, Tedna normally finished work without errors
